import { mkdir, readFile, writeFile } from 'node:fs/promises';

const mobileCss = `
@media(max-width:640px){html,body{overflow-x:hidden}main,article,section,div,p,h1,h2,h3,button,span{min-width:0;overflow-wrap:anywhere}.bar{padding:10px 14px;gap:10px}.brand{font-size:14px}.brand i{width:30px;height:30px}.tabs{gap:4px}.tabs button{padding:8px 11px;font-size:13px}.wrap{padding:22px 14px 56px}.hero{padding-bottom:18px}.hero h1,.page h1{font-size:32px;line-height:1.08;letter-spacing:-.045em}.hero p,.page p{font-size:14px;line-height:1.7}.eyebrow,.kicker{font-size:10px;letter-spacing:.11em}.share{padding:9px 12px;font-size:12px}.stats div{padding:16px 2px}.stats strong{font-size:20px}.stats span,.metric{font-size:10px}.cards{gap:10px;margin-top:22px}.card{border-radius:14px;padding:16px}.card strong{font-size:20px}.card p{font-size:13px;line-height:1.55}.grid{gap:26px;margin-top:30px}.head{display:block}.head h2{font-size:24px}.brief{border-radius:14px;padding:16px}.brief h3{font-size:16px;line-height:1.35;margin:12px 0 8px}.brief p{font-size:13px;line-height:1.65}.side{border-radius:14px;padding:16px}.timeline li{grid-template-columns:42px 1fr;gap:8px;padding:12px 0;font-size:13px}.coverage{border-radius:12px;padding:13px;font-size:12px}.subnav{overflow-x:auto;gap:6px;margin:18px 0}.subnav button{flex-shrink:0;padding:8px 12px;font-size:13px}.policy{border-radius:12px;padding:13px;font-size:13px}.mag{gap:22px;margin-top:20px}.index{margin-left:-14px;margin-right:-14px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:12px 14px}.index nav{display:flex;overflow-x:auto;gap:8px}.index a{min-width:180px;border-radius:12px;padding:11px}.issue{border-radius:18px;padding:20px}.issue h2{font-size:30px;line-height:1.12}.issue p{font-size:14px;line-height:1.72}.pills{gap:6px}.pills span{font-size:11px;padding:6px 8px}.lanes{padding:20px 0;margin-top:20px}.lanegrid a{padding:14px}.lanegrid p{font-size:13px;line-height:1.6}.read30{margin-top:20px;border-radius:14px;padding:16px}.chapter{display:block;padding:32px 0}.num{font-size:26px}.chapter h2{font-size:26px;line-height:1.18}.lead{font-size:15px;line-height:1.7}.sections{gap:10px;margin-top:18px}.sections section{border-radius:12px;padding:14px}.sections p{font-size:14px;line-height:1.7}.todo{margin-top:16px;padding:12px 0 12px 14px}.todo li{font-size:14px;line-height:1.55}.modal{align-items:stretch;padding:0}.box{width:100%;max-width:none;max-height:none;min-height:100vh;border-radius:0}.boxbar{padding:12px}.article{padding:16px;font-size:14px;line-height:1.7}.copy{padding:14px}}
`;

await mkdir('dist', { recursive: true });
const html = await readFile('index.html', 'utf8');
const nextHtml = html.includes('@media(max-width:640px)')
  ? html
  : html.replace('</style>', `${mobileCss}</style>`);
await writeFile('dist/index.html', nextHtml);
console.log('静态站点已构建到 dist/，并注入移动端阅读优化。');
